apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: nginx-pod
        image: nginx
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        ports:
        - containerPort: 80
