apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  selector:
    matchLabels:
      type: web-server
  replicas: 6
  template:
    metadata:
      name: my-pod
      labels:
        name: pod
        type: web-server
    spec:
      containers:
        - name: my-container
          image: httpd
