apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2 # Number of pods need to be created
  selector:
    matchLabels:
      app: nginx
  template: # Template describes the pods that will be created.
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          resources:
            limits:
              memory: 512Mi
              cpu: ".5"
          ports:
            - containerPort: 80
